/**
 * ivr-types.ts
 *
 * Core type definitions for the bilingual speech‑to‑speech IVR pipeline.
 * All types are immutable‑friendly and designed for event‑driven stream processing.
 */

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

/** Deterministic state machine for a single IVR session. */
export enum IVRSessionState {
  AWAITING_AUTH   = 'AWAITING_AUTH',
  IDLE            = 'IDLE',
  SPEAKING_TO_USER = 'SPEAKING_TO_USER',
  LISTENING_TO_USER = 'LISTENING_TO_USER',
  DISPATCHING_TRUNK = 'DISPATCHING_TRUNK',   // awaiting response from a Core Temporal Worker (P2P/Bill-Pay)
  TERMINATED      = 'TERMINATED',
}

// ---------------------------------------------------------------------------
// Language Support
// ---------------------------------------------------------------------------

/** Supported languages with their BCP‑47 tags. */
export type LanguageCode = 'uz-UZ' | 'ru-RU';

/** Minimum confidence required to switch languages mid‑call. */
export const LANGUAGE_SWITCH_CONFIDENCE_THRESHOLD = 0.85;

// ---------------------------------------------------------------------------
// Signed Identity
// ---------------------------------------------------------------------------

/**
 * Identity bundle signed by the authentication gateway.
 * Carries the customer identifier and claims needed for banking operations.
 */
export interface SignedIdentityContext {
  customerId: string;
  sessionClaims: Record<string, unknown>;  // e.g., { auth_level: 'FULL' }
  /** Compact JWS signature over the serialized claims. */
  signature: string;
}

// ---------------------------------------------------------------------------
// Conversation History
// ---------------------------------------------------------------------------

/** A single turn in the conversation. */
export interface Utterance {
  role: 'user' | 'bot';
  text: string;
  language: LanguageCode;
  timestamp: number; // ms since epoch
}

/** Mutable context carried through the session. */
export interface ConversationContext {
  activeLanguage: LanguageCode;
  languageConfidence: Record<LanguageCode, number>; // per‑language score
  history: Utterance[];
  identity: SignedIdentityContext;
  /** Set when the last user utterance contained a banking intent. */
  pendingIntent?: ExtractedIntent;
}

// ---------------------------------------------------------------------------
// Streaming Data Units
// ---------------------------------------------------------------------------

/** Raw PCM audio frame (16‑bit linear, 8 kHz). */
export interface AudioFrame {
  /** PCM samples as a byte array. */
  data: Uint8Array;
  /** Capture timestamp (ms since epoch). */
  timestamp: number;
}

/** Incremental or final result from the ASR engine. */
export interface AsrTranscript {
  text: string;
  isFinal: boolean;
  confidence: number;
  /** Detected language – may be omitted by some ASR providers. */
  language?: LanguageCode;
}

/** Single token emitted by the LLM during streaming. */
export interface LlmStreamToken {
  token: string;
}

// ---------------------------------------------------------------------------
// Banking Intents
// ---------------------------------------------------------------------------

/** Structure of a recognised banking intent extracted from a user utterance. */
export interface ExtractedIntent {
  intentName: 'P2P_TRANSFER' | 'PAY_BILL' | 'CHECK_BALANCE';
  entities: Record<string, string>;  // e.g., { amount: '100000', biller: 'COMMUNAL' }
  confidence: number;
  rawText: string;
}

/** Minimal payload passed to the Temporal boundary when an intent must be executed. */
export interface TransactionRequest {
  intent: ExtractedIntent;
  identity: SignedIdentityContext;
  callSessionId: string;
}

// ---------------------------------------------------------------------------
// External Service Interfaces (optional, can be expanded)
// ---------------------------------------------------------------------------

/**
 * Expected result from a Trunk workflow execution to pipe back to the user.
 */
export interface TransactionResult {
  success: boolean;
  /** Contextual message generated by the core worker to be spoken to the user (e.g., "Transfer complete") */
  ttsMessageToPlay: string;
}

/**
 * Interface for an external Temporal trigger.
 * Keeps the orchestrator completely decoupled from the Temporal SDK.
 */
export interface TemporalTrigger {
  executeTransaction(request: TransactionRequest): Promise<TransactionResult>;
}

/**
 * Minimal streaming ASR client contract.
 * In production this wraps a WebSocket or gRPC bidi stream.
 */
export interface StreamingASRClient {
  /**
   * Start recognition on a new audio stream.
   * @returns An async iterable of transcripts and a `close()` method.
   */
  startRecognition(
    language: LanguageCode,
    onSpeechStart?: () => void,
    onSpeechEnd?: () => void
  ): {
    transcriptIterable: AsyncIterable<AsrTranscript>;
    /** Feed an audio frame into the recognizer. */
    sendAudio(frame: AudioFrame): void;
    close(): void;
  };
}