// Package compliance implements all regulatory output for the revenant-orchestrator:
// SAR XML filing, PII scrubbing, forensic signing, and audit telemetry.
//
// sar.go — BLOCK 7.8: CBU Compliance Engine (Hardened v26.1)
// Mandate: LRU-1115 Article 14 — Automated Suspicious Activity Report generation.
//
// Trigger condition (set by internal/policy/invariants.go):
//
//	ctx.SARRequired == true  when  ctx.PolicyResult.AmountUSD >= sarThresholdUSD ($10,000)
//
// On success:
//   - Returns the serialised XML string.
//   - Populates ctx.SARPayload with metadata for the downstream dispatch queue.
//
// Architecture §4 invariant:
//
//	"XML fields MUST be escaped. Filed before dispatch, not after."
//	Go's encoding/xml handles escaping automatically via struct marshalling.
//	String fields tagged with `xml:",chardata"` are entity-encoded by the marshaller
//	before writing — no manual escapeXml() helper needed.
package compliance

import (
	"encoding/xml"
	"fmt"
	"strings"
	"time"

	"revenant-gateway/internal/domain"
)

// ─── CBU SAR SCHEMA CONSTANTS ─────────────────────────────────────────────────

const (
	// sarXMLNS is the CBU SAR v2 namespace. All SAR documents must carry this.
	// Source: architecture spec §4 "xmlns=http://cbu.uz/sar/v2"
	sarXMLNS = "http://cbu.uz/sar/v2"

	// sarThresholdUSD is the LRU-1115 Article 14 mandatory filing threshold.
	// Mirrors the constant in internal/policy/invariants.go — source of truth is policy.
	sarThresholdUSD = 10_000.0

	// sarQueueTarget is the internal routing key for the CBU reporting queue.
	sarQueueTarget = "CBU_REPORTING"

	// sarPriority is the alert priority for SAR filings.
	sarPriority = "P1_CRITICAL"

	// sarPolicyVersion is the REVENANT policy document under which this SAR is filed.
	sarPolicyVersion = "Revenant_v26.5_Article14"

	// sarMaxSubjectLen caps the customer subject embedded in the SAR to prevent
	// log injection via an oversized complaint subject field.
	sarMaxSubjectLen = 200
)

// ─── XML DOCUMENT STRUCTURE ───────────────────────────────────────────────────
//
// The struct hierarchy maps directly to the CBU SAR v2 XML schema.
// encoding/xml marshals the outer element name and namespace from XMLName.
//
// ESCAPING INVARIANT (Architecture §4):
//   All fields containing customer-derived data use xml:",chardata".
//   The xml package entity-encodes <, >, &, ', " automatically on Marshal.
//   This closes the log-injection attack vector that existed in the n8n
//   hand-rolled template (where a customer could embed XML tags in their
//   complaint subject to forge SAR content).
//
// NAMESPACE:
//   The XMLName field on SARDocument declares the default namespace.
//   All child elements inherit it without repeating the xmlns attribute.

// SARDocument is the root element of the CBU SAR v2 XML document.
type SARDocument struct {
	// XMLName carries the element name and default namespace.
	// xml.Marshal writes: <SuspiciousActivityReport xmlns="http://cbu.uz/sar/">
	XMLName xml.Name `xml:"SuspiciousActivityReport"`
	XMLNS   string   `xml:"xmlns,attr"`

	// Report identity
	ReportID      string `xml:"ReportID"`
	SchemaVersion string `xml:"SchemaVersion"`

	// Filing context
	ReportDate    string `xml:"ReportDate"`    // ISO 8601 UTC
	PolicyVersion string `xml:"PolicyVersion"` // Revenant_v26.5_Article14

	// Transaction data
	Transaction SARTransaction `xml:"Transaction"`

	// Subject (customer) data
	Subject SARSubject `xml:"Subject"`

	// Regulatory disposition
	Disposition SARDisposition `xml:"Disposition"`
}

// SARTransaction carries the financial transaction details.
// SARTransaction carries the financial transaction details.
type SARTransaction struct {
	TraceID         string `xml:"TraceID"`
	Amount          string `xml:"Amount"`   // formatted "NNNN.NN"
	Currency        string `xml:"Currency"` // USD | UZS
	AmountUSD       string `xml:"AmountUSD"`
	ReportingReason string `xml:"ReportingReason"` // <--- Removed ,chardata
}

// SARSubject carries PII-minimised information about the transaction originator.
// Full PII is in the forensic log (BLOCK 7.6). The SAR carries only enough to
// identify the report, not to reconstruct the full customer record.
// SARSubject carries PII-minimised information about the transaction originator.
type SARSubject struct {
	EmailDomain  string `xml:"EmailDomain"` // <--- Removed ,chardata
	Jurisdiction string `xml:"Jurisdiction"`
}

// SARDisposition carries the system's internal routing decision for this SAR.
type SARDisposition struct {
	Action      string `xml:"Action"`      // FILE_SAR_IMMEDIATE
	QueueTarget string `xml:"QueueTarget"` // CBU_REPORTING
	Priority    string `xml:"Priority"`    // P1_CRITICAL
	// AutoFiled indicates this was generated by the automated compliance engine.
	// A human officer must review and confirm within the regulatory window.
	AutoFiled bool `xml:"AutoFiled"`
}

// ─── GENERATE SAR ─────────────────────────────────────────────────────────────

// GenerateSAR implements BLOCK 7.8: CBU Compliance Engine.
//
// It MUST be called BEFORE the dispatch stage (Architecture §4: "Filed before dispatch,
// not after"). The caller in the worker pipeline is responsible for this ordering.
//
// Conditional trigger:
//
//	GenerateSAR is a no-op if ctx.SARRequired is false. The caller may invoke it
//	unconditionally — internal guard handles the condition. This avoids scattered
//	if-checks in the pipeline orchestration code.
//
// On successful generation:
//   - Returns the well-formed XML string.
//   - Populates ctx.SARPayload with the XML, reason, amount, and routing metadata.
//   - ctx.SARPayload.QueueTarget = "CBU_REPORTING" signals the dispatch layer.
//
// On error:
//   - Returns ("", err). ctx.SARPayload is NOT modified.
//   - Caller should treat SAR generation failure as FATAL for transactions above threshold.
func GenerateSAR(ctx *domain.IntentContext) (string, error) {
	// ── GUARD: SAR only required above $10,000 threshold ─────────────────
	if !ctx.SARRequired {
		return "", nil
	}

	now := time.Now().UTC()

	// ── REPORT ID: deterministic, idempotent ──────────────────────────────
	//
	// ReportID = "SAR-" + TraceID ensures:
	//   (1) Uniqueness within the system (TraceID is already globally unique).
	//   (2) Idempotency: filing the same transaction twice produces the same
	//       ReportID, which the CBU portal deduplicates on receipt.
	//   (3) Traceability: the CBU can cross-reference the ReportID against our
	//       internal audit ledger using the embedded TraceID.
	reportID := "SAR-" + ctx.TraceID

	// ── SUBJECT: PII minimisation ─────────────────────────────────────────
	//
	// The full customer email is NOT included. Only the domain portion is written
	// to the SAR. The full record is available in the forensic seal (BLOCK 7.6)
	// which is stored in the audit ledger under restricted access.
	emailDomain := extractEmailDomain(ctx.CustomerEmail)
	jurisdiction := deriveJurisdiction(emailDomain)

	// ── REPORTING REASON: safe for XML ────────────────────────────────────
	//
	// The reason string is sourced from our internal policy engine (not from
	// user input), so injection risk is low. We still clamp and sanitise it
	// because ctx.Subject (which may influence advisory text) is user-derived.
	reportingReason := buildReportingReason(ctx.PolicyResult.AmountUSD, sarThresholdUSD)

	// ── BUILD SAR DOCUMENT STRUCT ─────────────────────────────────────────
	doc := SARDocument{
		XMLNS:         sarXMLNS,
		ReportID:      reportID,
		SchemaVersion: "2.0",
		ReportDate:    now.Format(time.RFC3339),
		PolicyVersion: sarPolicyVersion,

		Transaction: SARTransaction{
			TraceID:         ctx.TraceID,
			Amount:          fmt.Sprintf("%.2f", ctx.TransactionAmt),
			Currency:        normaliseCurrency(ctx.Currency),
			AmountUSD:       fmt.Sprintf("%.2f", ctx.PolicyResult.AmountUSD),
			ReportingReason: reportingReason,
		},

		Subject: SARSubject{
			EmailDomain:  emailDomain,
			Jurisdiction: jurisdiction,
		},

		Disposition: SARDisposition{
			Action:      "FILE_SAR_IMMEDIATE",
			QueueTarget: sarQueueTarget,
			Priority:    sarPriority,
			AutoFiled:   true,
		},
	}

	// ── MARSHAL TO XML ────────────────────────────────────────────────────
	//
	// xml.MarshalIndent produces readable output for the CBU portal ingestion.
	// All chardata fields are automatically entity-encoded by the marshaller.
	// No manual escaping required or permitted — the struct tags handle it.
	raw, err := xml.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", fmt.Errorf("sar.GenerateSAR: xml.Marshal failed for trace=%s: %w",
			ctx.TraceID, err)
	}

	// Prepend the XML declaration. MarshalIndent does not add it automatically.
	xmlStr := xml.Header + string(raw)

	// ── POPULATE ctx.SARPayload ───────────────────────────────────────────
	//
	// SARPayload is the metadata record written to the dispatch queue.
	// The XML field carries the full document for the CBU portal.
	// The other fields allow the downstream queue router to prioritise and
	// route the SAR without parsing the XML.
	ctx.SARPayload = &domain.SARData{
		XML:             xmlStr,
		ReportingReason: reportingReason,
		AmountUSD:       ctx.PolicyResult.AmountUSD,
		Threshold:       sarThresholdUSD,
		Priority:        sarPriority,
		QueueTarget:     sarQueueTarget,
	}

	return xmlStr, nil
}

// ─── HELPERS ──────────────────────────────────────────────────────────────────

// extractEmailDomain returns the domain portion of an email address.
// Returns "unknown" if the address is malformed (missing @).
// Result is used only for the SAR subject — not for routing or authentication.
func extractEmailDomain(email string) string {
	idx := strings.LastIndex(email, "@")
	if idx < 0 || idx == len(email)-1 {
		return "unknown"
	}
	return strings.ToLower(email[idx+1:])
}

// deriveJurisdiction returns the ISO 3166-1 alpha-2 territory code inferred
// from the email domain's top-level suffix.
// Used in the SAR Subject.Jurisdiction field for CBU cross-border reporting.
func deriveJurisdiction(domain string) string {
	switch {
	case strings.HasSuffix(domain, ".uz"):
		return "UZ" // Republic of Uzbekistan
	case strings.HasSuffix(domain, ".ru"):
		return "RU"
	case strings.HasSuffix(domain, ".kz"):
		return "KZ" // Kazakhstan (common Uzbek diaspora banking)
	case strings.HasSuffix(domain, ".com"), strings.HasSuffix(domain, ".net"),
		strings.HasSuffix(domain, ".org"):
		return "INTERNATIONAL"
	default:
		return "UNKNOWN"
	}
}

// buildReportingReason produces the SAR reporting rationale string.
// Source: internal policy state only — NOT user-derived text.
// Architecture §4: "Log injection via SAR XML is a real attack vector."
// We never embed ctx.Subject or ctx.Body in the reporting reason.
func buildReportingReason(amountUSD, thresholdUSD float64) string {
	return fmt.Sprintf(
		"Transaction amount USD %.2f exceeds CBU LRU-1115 Article 14 mandatory "+
			"reporting threshold of USD %.0f. Automated SAR filing triggered by "+
			"REVENANT compliance engine policy %s.",
		amountUSD, thresholdUSD, sarPolicyVersion,
	)
}

// normaliseCurrency upper-cases the currency code and falls back to "USD"
// if the value is empty. Prevents a blank <Currency/> element in the SAR XML.
func normaliseCurrency(currency string) string {
	c := strings.ToUpper(strings.TrimSpace(currency))
	if c == "" {
		return "USD"
	}
	return c
}
