// enrollment-workflow.ts
//
// The Durable Path. A customer records three audio samples, almost
// certainly across multiple separate interactions over real wall-clock
// time (not three back-to-back calls in one HTTP request) — exactly the
// "wait for a real-world event with no thread cost while waiting" problem
// Temporal exists to solve, the same architectural reason P2P's
// CONFIRM_P2P and Credit's SIGN_LOAN are workflows rather than synchronous
// calls.

import {
  proxyActivities,
  defineSignal,
  defineQuery,
  setHandler,
  condition,
} from '@temporalio/workflow';
import type { EnrollmentState } from './biometric-types.js';

// ---------------------------------------------------------------------------
// Activity interface + retry policies
// ---------------------------------------------------------------------------

export interface SampleQualityValid {
  readonly outcome: 'VALID';
  readonly qualityScore: number;
}

export interface SampleQualityRejected {
  readonly outcome: 'REJECTED';
  readonly reason: 'TOO_NOISY' | 'TOO_SHORT' | 'CLIPPING_DETECTED';
}

export type SampleQualityResult = SampleQualityValid | SampleQualityRejected;

export function assertSampleQualityUnreachable(value: never): never {
  throw new Error(`Unreachable sample quality result: ${JSON.stringify(value)}`);
}

export interface EnrollmentActivities {
  evaluateSampleQuality(input: { audioFrameRef: string }): Promise<SampleQualityResult>;
  /**
   * Receives the three VALIDATED sample refs and is responsible for
   * extraction + aggregation + persistence as one unit — extracting and
   * averaging three independent embeddings into a single enrolled
   * voiceprint (a centroid across samples) is a standard technique for
   * reducing single-recording noise in speaker enrollment, not a
   * shortcut. Must be implemented idempotently against customerId (an
   * upsert, not a blind insert) — this is exactly the kind of
   * side-effecting, retried-on-failure Activity where a non-idempotent
   * implementation could leave a corrupted partial enrollment behind
   * after a retry, the same concern this project has flagged for every
   * other side-effecting financial Activity.
   */
  aggregateAndPersistVoiceprint(input: {
    customerId: string;
    sampleRefs: readonly string[];
  }): Promise<{ voiceprintId: string }>;
}

/** Per-sample quality check: fast, low-risk, moderate retry. */
const qualityActivities = proxyActivities<EnrollmentActivities>({
  startToCloseTimeout: '5 seconds',
  retry: {
    initialInterval: '500ms',
    backoffCoefficient: 2,
    maximumInterval: '5 seconds',
    maximumAttempts: 4,
  },
});

/**
 * Final persistence — the conservative profile, same philosophy as
 * Credit's disbursement and P2P's executeTransfer: this writes a durable
 * credential with real downstream security consequences. Capped at 2
 * attempts rather than retrying liberally into a possible duplicate or
 * corrupted enrollment record.
 */
const persistenceActivities = proxyActivities<EnrollmentActivities>({
  startToCloseTimeout: '10 seconds',
  retry: {
    initialInterval: '1 second',
    backoffCoefficient: 1,
    maximumAttempts: 2,
  },
});

const { evaluateSampleQuality } = qualityActivities;
const { aggregateAndPersistVoiceprint } = persistenceActivities;

// ---------------------------------------------------------------------------
// Signal & Query
// ---------------------------------------------------------------------------

/**
 * sampleId is generated by the CALLER (the ingress handler that receives
 * each recorded sample from the customer's device/Telegram), using real
 * randomness there — never inside this workflow. Per the strict
 * determinism constraint, this workflow function itself never calls
 * crypto.randomUUID() or Math.random(); every identifier it handles
 * arrives as data from outside its own execution.
 */
export interface AudioSampleReceivedSignalPayload {
  readonly sampleId: string;
  /** A storage reference, never raw audio bytes inline — same convention established for VLAN 10's VoicePayloadSchema. */
  readonly audioFrameRef: string;
}

export interface CancelEnrollmentSignalPayload {
  readonly reason: string;
}

export const audioSampleReceivedSignal = defineSignal<[AudioSampleReceivedSignalPayload]>('audioSampleReceived');
export const cancelEnrollmentSignal = defineSignal<[CancelEnrollmentSignalPayload]>('cancelEnrollment');

export interface EnrollmentStatusSnapshot {
  readonly state: EnrollmentState;
  readonly validSamplesCollected: number;
  readonly totalAttempts: number;
}

export const getEnrollmentStatusQuery = defineQuery<EnrollmentStatusSnapshot>('getEnrollmentStatus');

// ---------------------------------------------------------------------------
// Workflow input / result
// ---------------------------------------------------------------------------

export interface EnrollmentWorkflowInput {
  readonly traceId: string;
  readonly customerId: string;
}

interface EnrollmentOutcomeBase {
  readonly traceId: string;
  readonly customerId: string;
}

export interface EnrollmentCancelled extends EnrollmentOutcomeBase {
  readonly status: 'CANCELLED';
  readonly reason: string;
}

export interface EnrollmentTimedOut extends EnrollmentOutcomeBase {
  readonly status: 'TIMED_OUT';
}

export interface EnrollmentMaxAttemptsExceeded extends EnrollmentOutcomeBase {
  readonly status: 'MAX_ATTEMPTS_EXCEEDED';
  readonly totalAttempts: number;
}

export interface EnrollmentSucceeded extends EnrollmentOutcomeBase {
  readonly status: 'ENROLLED';
  readonly voiceprintId: string;
}

export interface EnrollmentAggregationFailed extends EnrollmentOutcomeBase {
  readonly status: 'AGGREGATION_FAILED';
  readonly errorDetail: string;
}

export type EnrollmentWorkflowResult =
  | EnrollmentCancelled
  | EnrollmentTimedOut
  | EnrollmentMaxAttemptsExceeded
  | EnrollmentSucceeded
  | EnrollmentAggregationFailed;

export function assertEnrollmentUnreachable(value: never): never {
  throw new Error(`Unreachable enrollment workflow result: ${JSON.stringify(value)}`);
}

// ---------------------------------------------------------------------------
// Workflow
// ---------------------------------------------------------------------------

const REQUIRED_VALID_SAMPLE_COUNT = 3;

/**
 * Bounds the TOTAL number of submission attempts, not just valid ones —
 * without this, a customer (or an attacker) repeatedly submitting noisy
 * or invalid audio could keep this workflow alive indefinitely. Counting
 * attempts rather than elapsed wall-clock time, deliberately: this is a
 * pure in-memory counter incremented by workflow code itself, which is
 * fully deterministic (no wall-clock read required), unlike trying to
 * bound this by checking "how much real time has passed."
 */
const MAX_TOTAL_ATTEMPTS = 10;

/**
 * Per-attempt wait window. Notably, this does NOT require reading
 * Date.now() anywhere — Temporal's own `condition()` timeout parameter is
 * itself a deterministic, replay-safe timer primitive implemented at the
 * SDK level, not by this workflow function reading wall-clock time. The
 * strict "no Date.now()" constraint is satisfied by construction here,
 * not by careful avoidance.
 */
const PER_ATTEMPT_WAIT_TIMEOUT = '30 minutes';

interface ValidatedSample {
  readonly sampleId: string;
  readonly audioFrameRef: string;
  readonly qualityScore: number;
}

export async function VoiceprintEnrollmentWorkflow(
  input: EnrollmentWorkflowInput,
): Promise<EnrollmentWorkflowResult> {
  const pendingQueue: AudioSampleReceivedSignalPayload[] = [];
  const validSamples: ValidatedSample[] = [];
  let totalAttempts = 0;
  let cancelled = false;
  let cancelReason = '';
  let state: EnrollmentState = 'AWAITING_SAMPLES';

  setHandler(audioSampleReceivedSignal, (payload) => {
    pendingQueue.push(payload);
  });
  setHandler(cancelEnrollmentSignal, (payload) => {
    cancelled = true;
    cancelReason = payload.reason;
  });
  setHandler(getEnrollmentStatusQuery, () => ({
    state,
    validSamplesCollected: validSamples.length,
    totalAttempts,
  }));

  while (validSamples.length < REQUIRED_VALID_SAMPLE_COUNT) {
    if (cancelled) {
      state = 'FAILED';
      return { status: 'CANCELLED', traceId: input.traceId, customerId: input.customerId, reason: cancelReason };
    }

    if (totalAttempts >= MAX_TOTAL_ATTEMPTS) {
      state = 'FAILED';
      return {
        status: 'MAX_ATTEMPTS_EXCEEDED',
        traceId: input.traceId,
        customerId: input.customerId,
        totalAttempts,
      };
    }

    state = 'AWAITING_SAMPLES';
    const settled = await condition(() => pendingQueue.length > 0 || cancelled, PER_ATTEMPT_WAIT_TIMEOUT);

    if (cancelled) {
      state = 'FAILED';
      return { status: 'CANCELLED', traceId: input.traceId, customerId: input.customerId, reason: cancelReason };
    }

    if (!settled || pendingQueue.length === 0) {
      state = 'FAILED';
      return { status: 'TIMED_OUT', traceId: input.traceId, customerId: input.customerId };
    }

    // shift() on this workflow's own local array is deterministic — it's
    // mutating in-memory state derived entirely from signal payloads
    // already recorded in workflow history, not introducing any new
    // non-deterministic input.
    const nextSample = pendingQueue.shift()!;
    totalAttempts += 1;
    state = 'PROCESSING';

    const qualityResult = await evaluateSampleQuality({ audioFrameRef: nextSample.audioFrameRef });

    switch (qualityResult.outcome) {
      case 'VALID':
        validSamples.push({
          sampleId: nextSample.sampleId,
          audioFrameRef: nextSample.audioFrameRef,
          qualityScore: qualityResult.qualityScore,
        });
        break;
      case 'REJECTED':
        // Sample rejected, NOT a workflow failure — the loop continues
        // and simply waits for another submission. A single noisy
        // recording shouldn't end the whole enrollment attempt.
        break;
      default:
        assertSampleQualityUnreachable(qualityResult);
    }
  }

  state = 'PROCESSING';
  try {
    const persisted = await aggregateAndPersistVoiceprint({
      customerId: input.customerId,
      sampleRefs: validSamples.map((sample) => sample.audioFrameRef),
    });
    state = 'ENROLLED';
    return {
      status: 'ENROLLED',
      traceId: input.traceId,
      customerId: input.customerId,
      voiceprintId: persisted.voiceprintId,
    };
  } catch (err) {
    state = 'FAILED';
    return {
      status: 'AGGREGATION_FAILED',
      traceId: input.traceId,
      customerId: input.customerId,
      errorDetail: err instanceof Error ? err.message : 'Voiceprint aggregation and persistence failed.',
    };
  }
}